### ISSUE TITLE
Can not find the source code for convertIdentifiers function

### ISSUE THREAD

**Issue by nfancy** [sales-lab/graphite#2]
Hi 

I wanted to use some arguments used by org.hs.db package in your convertidentifiers function but could not find the source code.

**Comment by gbrsales** [comment]
Hi @nfancy,

`convertIdentifiers` is a generic function. It has multiple implementations for different S4 objects.

You can find the implementation for `Pathway` here: https://github.com/sales-lab/graphite/blob/1a22e1043a4b550780d00c2f15b9907cb2f54cef/R/conversion.R#L74
